# Generated by Django 6.0.3 on 2026-03-20 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaSacaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome da categoria/tipo do saco', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada (+)'), ('saida', 'Saída (-)')], max_length=10)),
                ('quantidade', models.PositiveIntegerField()),
                ('data_movimentacao', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(help_text='Quem da produção/estoque registrou?', max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SacoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_referencia', models.CharField(blank=True, help_text='Código interno, se houver', max_length=50, null=True, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('estoque_minimo', models.IntegerField(default=100, help_text='Limite para alertar o vendedor no sistema')),
                ('ativo', models.BooleanField(default=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sacos', to='products.categoriasacaria')),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='saco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentacoes', to='products.sacoreserva'),
        ),
    ]
